services:
  postgres:
    image: postgres:15
    container_name: bookstore_db
    environment:
      POSTGRES_DB: bookstore
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - rag_network

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    networks:
      - rag_network

  milvus:
    image: milvusdb/milvus:latest
    container_name: milvus
    ports:
      - "19530:19530"
      - "9091:9091"
    environment:
      ETCD_CFG.auto-compaction-retention: "1"
    volumes:
      - milvus_data:/var/lib/milvus
    networks:
      - rag_network

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    networks:
      - rag_network

  app:
    build: .
    container_name: rag-testing
    volumes:
      - .:/app
    depends_on:
      - qdrant
      - milvus
      - postgres
      - ollama
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - MILVUS_HOST=milvus
      - MILVUS_PORT=19530
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=bookstore
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - OLLAMA_HOST=ollama
      - OLLAMA_PORT=11434
    networks:
      - rag_network
    command: "tail -f /dev/null"

networks:
  rag_network:
    driver: bridge

volumes:
  qdrant_storage:
  milvus_data:
  postgres_data:
  ollama_data: 