database:
  connection_string: "postgresql://admin:admin123@postgres:5432/bookstore"

databases:
  qdrant:
    host: ${QDRANT_HOST:-localhost}
    port: ${QDRANT_PORT:-6333}
    collection_name: test_collection
    vector_size: 384

embedding:
  model_name: "BAAI/bge-small-en-v1.5" 

llm:
  host: "ollama"
  port: 11434
  model: "llama3.2:1b"
  parameters:
    num_gpu: 1
    num_thread: 4
    temperature: 0.7
    top_p: 0.9 