database:
  connection_string: "postgresql://admin:admin123@postgres:5432/bookstore"

databases:
  qdrant:
    host: ${QDRANT_HOST:-localhost}
    port: ${QDRANT_PORT:-6333}
    collection_name: test_collection
    vector_size: 384

embedding:
  model_name: "BAAI/bge-small-en-v1.5" 