database:
  connection_string: "postgresql://user:password@localhost:5432/dbname"

databases:
  qdrant:
    collection_name: "sql_schemas"
    vector_size: 384
    host: "localhost"
    port: 6333

embedding:
  model_name: "BAAI/bge-small-en-v1.5" 